version: '3.8'

services:

  postgres-fastapi:
    image: postgres:14.5
    expose:
      - ${POSTGRES_EXPOSE}
    healthcheck:
      test: "pg_isready --username=postgres && psql --username=postgres --list"
      timeout: 10s
      retries: 20
    restart: always
    env_file:
      - .env.sample

  redis:
    image: redis:7.0.5
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    expose:
      - ${REDIS_PORT}
    depends_on:
      - postgres-fastapi
    env_file:
      - .env.sample

  backend:
    build: .
    ports:
      - ${PROJECT_PORT}:${PROJECT_PORT}
    volumes:
      - ./src/files:/code/src/files/
    env_file:
      - .env.sample
    depends_on:
      postgres-fastapi:
        condition: service_healthy
      redis:
        condition: service_healthy

  nginx:
    image: nginx:1.19.3
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    volumes:
      - ./services/nginx.conf:/etc/nginx/conf.d/site.conf.template
      - ./src/files:/code/src/files/
    command: sh -c "${COMMANDS_BEFORE_START_NGINX}"
    restart: always
    env_file:
      - .env.sample

    depends_on:
      - backend